### ISSUE TITLE
Hombrige Unraid Docker no port mapping?

### ISSUE THREAD

**Issue by 10bn** [SiwatINC/unraid-ca-repository#4]
Somehow the hombridge docker lost it's portmapping since the last update. Or probably im doing something wrong. I tryed a clean setup but it's not working out of the box anymore. 

![image](https://user-images.githubusercontent.com/46263124/50548147-1ae67400-0c48-11e9-99e6-9ff658327cd3.png)

**Comment by SiwatS** [comment]
Can I see your log?

**Comment by jhandel** [comment]
I see the same problem.. here is what my homebridge with UI image looks like when I first try to create it.. 

![image](https://user-images.githubusercontent.com/308604/52670913-6646a000-2edf-11e9-9d58-c01f8ccb6cb6.png)

**Comment by SiwatS** [comment]
Port mapping is not an option from the start, the network need to be host for broadcast and multicast packet, port can be change in the config file
